#!/bin/sh
#
# OpenGrok Wrapper (Interactive GUI, Initial Generation and Cron Job Updating)
#
# $Id$
#
# Based on the ideas and code in run.sh & run-quiet.sh
#

#
# Usage
#

Usage()
{
    echo 1>&2
    echo "Usage: ${0} <update|updateQuietly|updateConfiguration|usage|gui>" 1>&2
    echo 1>&2
    exit 1
}

#
# Configuration
#
if [ -n "${OPENGROK_CONFIGURATION}" -a -f "${OPENGROK_CONFIGURATION}" ]
then
    # Load the local OpenGrok Configuration Environment
    . "${OPENGROK_CONFIGURATION}"
else
    # Use the built-in defaults. This section can be copied to its own
    # file and tailored to your local requirements. Then simply set 
    # OPENGROK_CONFIGURATION=/path/to/your/configuration, before using
    # this wrapper. It will save you hand editting in your settings
    # on each new release. Sample Cron Entry might look like:
    # 15 0 * * * OPENGROK_CONFIGURATION=/pkgs/etc/OpenGrok.sh /pkgs/sbin/OpenGrok updateQuietly

    # Setup a standard execution environment
    if [ -f /pkgs/sbin/CronExecutionEnvironment.sh ]
    then
	. /pkgs/sbin/CronExecutionEnvironment.sh
    fi

    # Source Code/Repository Root
    SRC_ROOT="/data/opengrok/src"

    # OpenGrok Data Root (for Lucene index and hypertext cross-references)
    DATA_ROOT="/data/opengrok/data"

    # Optional Path to Description Mapping (Tab Separated Value)
    PATH_DESC="/data/opengrok/etc/paths.tsv"

    # XML Configuration
    XML_CONFIGURATION="/data/opengrok/configuration.xml"

    # Java Archive of OpenGrok
    OPENGROK_JAR="/data/opengrok/opengrok.jar"

    # Exubrant CTags (http://ctags.sf.net)
    EXUBRANT_CTAGS="/pkgs/64-bit/release/ctags-5.7/bin/ctags"

    # Java Home
    JAVA_HOME="/usr/jdk/instances/jdk1.6.0"
    export JAVA_HOME

    # Java Virtual Machine
    JAVA="${JAVA_HOME}/bin/java"

    # Uncomment the following line if your source contains Mercurial repositories.
    SCAN_FOR_REPOSITORY="-S"

    # Properties
    PROPERTIES="-Dorg.opensolaris.opengrok.history.Mercurial=/pkgs/64-bit/bin/hg"

    # JVM Options
    #JAVA_OPTS="-server -Xmx1024m"

    # An update program for EftarFile
    # Usage: <class> inputFile [inputFile ...] outputFile
    # EftarFile == An Extremely Fast Tagged Attribute Read-only File System
    EFTAR_UPDATE="org.opensolaris.opengrok.web.EftarFile"

    # Generated EftarFile
    EFTAR_OUTPUT_FILE="${DATA_ROOT}/index/dtags.eftar"

    # Be Quiet? (set indirectly by command line arguments in the main program)
    QUIET=

    # or alternatively, Be Verbose!
    VERBOSE="-v"
fi

#
# Implementation
#

# The variable "DO" can usefully be set to "echo" to aid in script debugging

StdInvocation()
{
    ${DO} ${JAVA} ${JAVA_OPTS} ${PROPERTIES}			\
	-jar ${OPENGROK_JAR}					\
	${SCAN_FOR_REPOSITORY} ${VERBOSE} ${QUIET}		\
	${EXUBRANT_CTAGS:+-c} ${EXUBRANT_CTAGS}			\
	-s ${SRC_ROOT} -d ${DATA_ROOT}				\
	"${@}"
}

UpdateGeneratedConfiguration()
{
    StdInvocation -W ${XML_CONFIGURATION}
}

UpdateGeneratedData()
{
    StdInvocation -H
}

UpdateDescriptionCache()
{
    # OPTIONAL : Update the EftarFile data
 
    if [ -n "${PATH_DESC}" -o -s "${PATH_DESC}" ]
    then
	${DO} ${JAVA} -classpath ${OPENGROK_JAR}		\
	    ${EFTAR_UPDATE} ${PATH_DESC} ${EFTAR_OUTPUT_FILE}
    fi
}

InvokeGUI()
{
    ${DO} ${JAVA} ${JAVA_OPTS} -jar ${OPENGROK_JAR} &
}

OpenGrokUsage()
{
    ${DO} ${JAVA} ${JAVA_OPTS} -jar ${OPENGROK_JAR} '-?'
}

#
# Main Program
#

if [ $# -ne 1 ]
then
    Usage
fi

case "${1}" in

    update)
	UpdateGeneratedData
	UpdateDescriptionCache
	;;

    updateQuietly)
	QUIET="-q"
	VERBOSE=""
	UpdateGeneratedData
	UpdateDescriptionCache
	;;

    updateConfiguration)
	UpdateGeneratedConfiguration
	;;

    usage)
        OpenGrokUsage
	;;

    gui)
	InvokeGUI
	;;

    *)
        Usage
	;;

esac

#
# End of File
#
